// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iepzhimroilxkpxfnvng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllcHpoaW1yb2lseGtweGZudm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTQ5NzYsImV4cCI6MjA2NjYzMDk3Nn0.e65DPhhcsFO_NAwHnc2mtlfEPisdmqswbvnG0R_wwzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);